stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  script:
    - docker build -t node-app:latest .
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "Testing..."

push_job:
  stage: push_to_dockerhub
  script:
    - docker login -u $DOCKEHUB_USER -P $DOCKERHUB_PASS
    - docker image tag node-app:latest $DOCKEHUB_USER/node-app:latest 
    - docker push $DOCKEHUB_USER/node-app:latest
  tags:
    - dev

deploy_job:
  stage:
  script:  
    - docker-compose up -d
  tags:
    - dev    
